services:
  py-app1:
    build:
      context: .
      dockerfile: projects/py-app1/Containerfile
    environment:
      PY_APP1_PORT: "${PY_APP1_PORT}"
      PY_APP1_TOKEN_HEADER_VALUE: "${PY_APP1_TOKEN_HEADER_VALUE}"
      PY_APP1_TOKEN_QUERY_VALUE: "${PY_APP1_TOKEN_QUERY_VALUE}"
    ports:
      - "${PY_APP1_PORT}:${PY_APP1_PORT}"
    volumes:
      - uv-cache:/root/.cache/uv
      - nix-store:/nix
      - nix-cache:/root/.cache/nix

  js-app2:
    build:
      context: .
      dockerfile: projects/js-app2/Containerfile
    depends_on:
      - py-app1
    environment:
      JS_APP1_URL: "${JS_APP1_URL}"
      JS_APP2_PORT: "${JS_APP2_PORT}"
      PY_APP1_URL: "http://py-app1:${PY_APP1_PORT}"
      PY_APP1_TOKEN_QUERY_VALUE: "${PY_APP1_TOKEN_QUERY_VALUE}"
    ports:
      - "${JS_APP2_PORT}:${JS_APP2_PORT}"
    volumes:
      - pnpm-store:/root/.local/share/pnpm/store
      - nix-store:/nix
      - nix-cache:/root/.cache/nix

  js-app1:
    build:
      context: .
      dockerfile: projects/js-app1/Containerfile
    depends_on:
      - js-app2
    environment:
      JS_APP1_PORT: "${JS_APP1_PORT}"
      VITE_JS_APP2_URL: "${VITE_JS_APP2_URL}"
    ports:
      - "${JS_APP1_PORT}:${JS_APP1_PORT}"
    volumes:
      - pnpm-store:/root/.local/share/pnpm/store
      - nix-store:/nix
      - nix-cache:/root/.cache/nix

volumes:
  pnpm-store:
  uv-cache:
  nix-store:
  nix-cache:
